@startuml

left to right direction

actor "Project Manager" as PM
actor "Developer" as DV 

rectangle "Workflow Management" {
  usecase "change time for Activity" as changeActivityTime 
  usecase "Set time for Regular Activity" as sTfRA
  usecase "Add Developer to Project" as aDtP
  usecase "Delete Developer from Project" as dDtP
  usecase "Register time on Activity" as rToA 
  usecase "Set Activity to Finished" as sAtF
  usecase "Get Activity Overview" as gAO

  sTfRA .up.> changeActivityTime: <<include>>

  rToA-[hidden]right->sTfRA
  sTfRA-[hidden]right->sAtF
  gAO-[hidden]right->rToA

}

PM --> changeActivityTime 
PM --> aDtP
PM -> dDtP

DV -up-> sTfRA 
DV -up-> rToA 
DV -up->sAtF
DV -up-> gAO




@enduml