@startuml

left to right direction

actor "Project Manager" as PM
actor "Developer" as DV 

rectangle "Workflow Management" {
  usecase "create Project" as createProject 
  usecase "mark a Project finished" as markProject
  usecase "add Activity to a Project" as addActivity
  usecase "delete Activity from a Project" as deleteActivity
  usecase "create a report about the Project" as createReport
  usecase "add Projectleader to Project" as addProjectLeader
  
  createProject -[hidden]right- addActivity
  markProject -[hidden]right- deleteActivity

}

PM --> createProject
PM --> markProject
PM --> addActivity
PM --> deleteActivity 
PM --> createReport
PM --> addProjectLeader


@enduml